# Generated by Django 5.2 on 2025-07-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("normalized_name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.ManyToManyField(blank=True, to="accounts.userinterest"),
        ),
    ]
