# Generated by Django 5.2.5 on 2025-08-27 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userinterest_userprofile_interests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="persona",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.CreateModel(
            name="SavedMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university", models.CharField(max_length=200)),
                ("course", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
                ("requirements", models.CharField(max_length=300)),
                ("course_link", models.URLField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserInterest",
        ),
        migrations.DeleteModel(
            name="UserPersona",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
