# Generated by Django 5.2.5 on 2025-09-03 05:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_userprofile_interests_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedmatch",
            old_name="type",
            new_name="course_type",
        ),
    ]
