# Generated by Django 5.2 on 2025-10-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_type_savedmatch_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedmatch",
            name="course_link",
            field=models.URLField(max_length=500),
        ),
    ]
