# Generated by Django 5.2 on 2025-08-27 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coursefinder", "001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("university", "name")},
        ),
    ]
