# Generated by Django 5.2 on 2025-08-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coursefinder", "0002_alter_course_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="link",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="university",
            name="all_courses_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="university",
            name="website",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
