# Generated by Django 5.2.5 on 2025-09-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "coursefinder",
            "0003_alter_course_link_alter_university_all_courses_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="mode",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
